# Generated by Django 5.0.2 on 2024-02-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimage',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimage',
            name='gender',
            field=models.CharField(blank=True, default='NA', max_length=10),
        ),
    ]
